# Занятие №3

In [4]:
import numpy as np
import pandas as pd

# Домашнее задание

In [45]:
# 1. Привести различные способы создания объектов типа Series
lst = [1, 2, 3, 4, 5]
data_lst = pd.Series(data=lst, index=["a", "b", "c", "d", "e"], name="Python list")
print("через список Python", data_lst)

array = np.array([1, 2, 3, 4, 5])
data_array = pd.Series(data=array, index=["a", "b", "c", "d", "e"], name="array NumPy")
print("через массив NumPy", data_array)

scalar = 666
data_scalar = pd.Series(data=scalar, index=["a", "b", "c", "d", "e"], name="scalar")
print("через скаляр", data_scalar)

dct = {
    "city1": 1,
    "city2": 2,
    "city3": 3,
    "city4": 4,
    "city5": 5,
}
data_dict = pd.Series(data=dct, name="Python dict")
print("через список Python", data_dict)

через список Python a    1
b    2
c    3
d    4
e    5
Name: Python list, dtype: int64
через массив NumPy a    1
b    2
c    3
d    4
e    5
Name: array NumPy, dtype: int64
через скаляр a    666
b    666
c    666
d    666
e    666
Name: scalar, dtype: int64
через список Python city1    1
city2    2
city3    3
city4    4
city5    5
Name: Python dict, dtype: int64


In [46]:
# 2. Привести различные способы создания объектов типа DataFrame
lst = [1, 2, 3, 4, 5]
lst1 = [6, 7, 8, 9, 10]
data_lst = pd.Series(data=lst)
data_lst1 = pd.Series(data=lst1)
data = pd.DataFrame({"column1": lst, "columns2": lst1})
print("через объекты Series")
print(data)

lst = [{"city": "city1", "city1": 1}, {"city": "city2", "city2": 2}]
data = pd.DataFrame(lst).set_index("city")
print("через список словарей")
print(data)

dat = {
    "column1": [1, 2, 3, 4, 5],
    "column2": [6, 7, 8, 9, 10],
}
data = pd.DataFrame(dat, index=["a", "b", "c", "d", "e"])
print("через словари объектов Series")
print(data)

array = np.array([[1, 6], [2, 7], [3, 8], [4, 9], [5, 10]])
data = pd.DataFrame(dat, index=["a", "b", "c", "d", "e"])
print("через двумерный массив NumPy")
print(data)

dtype = [("column1", int), ("column2", int)]
array = np.array([(1, 6), (2, 7), (3, 8), (4, 9), (5, 10)], dtype=dtype)
data = pd.DataFrame(dat)
print("структурированный массив NumPy")
print(data)

через объекты Series
   column1  columns2
0        1         6
1        2         7
2        3         8
3        4         9
4        5        10
через список словарей
       city1  city2
city               
city1    1.0    NaN
city2    NaN    2.0
через словари объектов Series
   column1  column2
a        1        6
b        2        7
c        3        8
d        4        9
e        5       10
через двумерный массив NumPy
   column1  column2
a        1        6
b        2        7
c        3        8
d        4        9
e        5       10
структурированный массив NumPy
   column1  column2
0        1        6
1        2        7
2        3        8
3        4        9
4        5       10


In [47]:
# 3. Объедините два объекта Series с неодинаковыми множествами ключей (индексов) так, чтобы вместо NaN было установлено значение 1
popular = pd.Series(
    {
        "city1": 1001,
        "city2": 1002,
        "city3": 1003,
        "city41": 1004,
        "city51": 1005,
    }
)
area = pd.Series(
    {
        "city1": 9991,
        "city2": 9992,
        "city3": 9993,
        "city42": 9994,
        "city52": 9995,
    }
)
data = pd.DataFrame({"area": area, "popular": popular}).fillna(1)
print(data)

          area  popular
city1   9991.0   1001.0
city2   9992.0   1002.0
city3   9993.0   1003.0
city41     1.0   1004.0
city42  9994.0      1.0
city51     1.0   1005.0
city52  9995.0      1.0


In [48]:
# 4. Переписать пример с транслирование для DataFrame так, чтобы вычитание происходило по СТОЛБЦАМ
A = rng.integers(0, 10, (3, 4))
df = pd.DataFrame(A, columns=["a", "b", "c", "d"])

print("DataFrame:")
print(df)

print("Первый столбец:")
print(df.iloc[:, 0])

print("Вычитание по столбцам:")
print(df.sub(df.iloc[:, 0], axis=0))

DataFrame:
   a  b  c  d
0  8  3  4  7
1  1  3  1  4
2  9  1  3  4
Первый столбец:
0    8
1    1
2    9
Name: a, dtype: int64
Вычитание по столбцам:
   a  b  c  d
0  0 -5 -4 -1
1  0  2  0  3
2  0 -8 -6 -5


In [49]:
# 5. На примере объектов DataFrame продемонстрируйте использование методов ffill() и bfill()
data = {
    "A": [1, np.nan, 3, np.nan, 5],
    "B": [np.nan, 7, np.nan, 9, np.nan],
    "C": [10, 20, np.nan, np.nan, 50],
}

df = pd.DataFrame(data)
print("Исходный DataFrame:")
print(df)

# ffill() заполняет пропуски ПОСЛЕДНИМ известным значением сверху вниз:
df1 = df.ffill()
print("После ffill():")
print(df1)

# bfill() заполняет пропуски СЛЕДУЮЩИМ известным значением снизу вверх:
df2 = df.bfill()
print("После bfill():")
print(df2)

Исходный DataFrame:
     A    B     C
0  1.0  NaN  10.0
1  NaN  7.0  20.0
2  3.0  NaN   NaN
3  NaN  9.0   NaN
4  5.0  NaN  50.0
После ffill():
     A    B     C
0  1.0  NaN  10.0
1  1.0  7.0  20.0
2  3.0  7.0  20.0
3  3.0  9.0  20.0
4  5.0  9.0  50.0
После bfill():
     A    B     C
0  1.0  7.0  10.0
1  3.0  7.0  20.0
2  3.0  9.0  50.0
3  5.0  9.0  50.0
4  5.0  NaN  50.0


Pandas - расширение NumPy (структурированные массивы). Строки и столбцы индексируются метками, а не только числовыми значениями

Series, DataFrame, Index

### Series

In [4]:
data = pd.Series([0.25, 0.5, 0.75, 1])
print(data)
print(type(data))

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64
<class 'pandas.core.series.Series'>


In [7]:
print(data.values, type(data.values))
print(data.index, type(data.index))

[0.25 0.5  0.75 1.  ] <class 'numpy.ndarray'>
RangeIndex(start=0, stop=4, step=1) <class 'pandas.core.indexes.range.RangeIndex'>


In [9]:
data = pd.Series([0.25, 0.5, 0.75, 1])
print(data)
print(data[0])
print(data[1:3])

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64
0.25
1    0.50
2    0.75
dtype: float64


In [11]:
data = pd.Series([0.25, 0.5, 0.75, 1], index=["a", "b", "c", "d"])
print(data)
print(data["a"])
print(data["b":"d"])

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
0.25
b    0.50
c    0.75
d    1.00
dtype: float64


In [12]:
print(data.index, type(data.index))

Index(['a', 'b', 'c', 'd'], dtype='object') <class 'pandas.core.indexes.base.Index'>


In [15]:
data = pd.Series([0.25, 0.5, 0.75, 1], index=[1, 10, 7, "d"])
print(data)
print(data[1])
print(data[10:"d"])

1     0.25
10    0.50
7     0.75
d     1.00
dtype: float64
0.25
10    0.50
7     0.75
d     1.00
dtype: float64


In [18]:
popular_dict = {
    "city1": 1001,
    "city2": 1002,
    "city3": 1003,
    "city4": 1004,
    "city5": 1005,
}
population = pd.Series(popular_dict)
print(population)
print(population["city4"])
print(population["city4":"city5"])

city1    1001
city2    1002
city3    1003
city4    1004
city5    1005
dtype: int64
1004
city4    1004
city5    1005
dtype: int64


Для создания Series можно использовать

- списки Python или массивы NumPy

- скалярные значения

- словари

## 1. Привести различные способы создания объектов типа Series

Для создания Series можно использовать
- списки Python или массивы NumPy
- скалярные значение
- словари

In [7]:
lst=[1,2,3,4,5]
data_lst = pd.Series(data=lst, index=["a", "b", "c", "d",'e'],name='Python list')
print('через список Python',data_lst)

array=np.array([1,2,3,4,5])
data_array = pd.Series(data=array, index=["a", "b", "c", "d", "e"], name="array NumPy")
print("через массив NumPy", data_array)

scalar=666
data_scalar = pd.Series(data=scalar, index=["a", "b", "c", "d", "e"], name="scalar")
print("через скаляр", data_scalar)

dct = {
    "city1": 1,
    "city2": 2,
    "city3": 3,
    "city4": 4,
    "city5": 5,
}
data_dict = pd.Series(data=dct, name="Python dict")
print("через список Python", data_dict)

через список Python a    1
b    2
c    3
d    4
e    5
Name: Python list, dtype: int64
через массив NumPy a    1
b    2
c    3
d    4
e    5
Name: array NumPy, dtype: int64
через скаляр a    666
b    666
c    666
d    666
e    666
Name: scalar, dtype: int64
через список Python city1    1
city2    2
city3    3
city4    4
city5    5
Name: Python dict, dtype: int64


### DataFrame

DataFrame - двумерный массив с явно определенными 

In [5]:
popular_dict = {
    "city1": 1001,
    "city2": 1002,
    "city3": 1003,
    "city4": 1004,
    "city5": 1005,
}
area_dict = {
    "city1": 9991,
    "city2": 9992,
    "city3": 9993,
    "city4": 9994,
    "city5": 9995,
}
population = pd.Series(popular_dict)
area = pd.Series(area_dict)
print(population)
print(area)

city1    1001
city2    1002
city3    1003
city4    1004
city5    1005
dtype: int64
city1    9991
city2    9992
city3    9993
city4    9994
city5    9995
dtype: int64


In [20]:
states = pd.DataFrame({"population": population, "area": area})
print(states)

       population  area
city1        1001  9991
city2        1002  9992
city3        1003  9993
city4        1004  9994
city5        1005  9995


In [21]:
print(states.values, type(states.values))
print(states.index, type(states.index))
print(states.columns, type(states.columns))

[[1001 9991]
 [1002 9992]
 [1003 9993]
 [1004 9994]
 [1005 9995]] <class 'numpy.ndarray'>
Index(['city1', 'city2', 'city3', 'city4', 'city5'], dtype='object') <class 'pandas.core.indexes.base.Index'>
Index(['population', 'area'], dtype='object') <class 'pandas.core.indexes.base.Index'>


In [22]:
print(states["area"])

city1    9991
city2    9992
city3    9993
city4    9994
city5    9995
Name: area, dtype: int64


DataFrame. Способы создания

- через объекты Series

- списки словарей

- словари объектов Series

- двумерный массив NumPy

- структурированный массив NumPy

## 2. Привести различные способы создания объектов DataFrame

In [27]:
lst = [1, 2, 3, 4, 5]
lst1 = [6, 7, 8, 9, 10]
data_lst = pd.Series(data=lst)
data_lst1 = pd.Series(data=lst1)
data = pd.DataFrame({"column1": lst, "columns2": lst1})
print("через объекты Series")
print(data)

lst = [{"city": "city1", "city1": 1}, {"city": "city2", "city2": 2}]
data = pd.DataFrame(lst).set_index("city")
print("через список словарей")
print(data)

dat = {
    "column1": [1, 2, 3, 4, 5],
    "column2": [6, 7, 8, 9, 10],
}
data = pd.DataFrame(dat, index=["a", "b", "c", "d", "e"])
print("через словари объектов Series")
print(data)

array = np.array([[1, 6], [2, 7], [3, 8], [4, 9], [5, 10]])
data = pd.DataFrame(dat, index=["a", "b", "c", "d", "e"])
print("через двумерный массив NumPy")
print(data)

dtype = [("column1", int), ("column2", int)]
array = np.array([(1, 6), (2, 7), (3, 8), (4, 9), (5, 10)], dtype=dtype)
data = pd.DataFrame(dat)
print("структурированный массив NumPy")
print(data)

через объекты Series
   column1  columns2
0        1         6
1        2         7
2        3         8
3        4         9
4        5        10
через список словарей
       city1  city2
city               
city1    1.0    NaN
city2    NaN    2.0
через словари объектов Series
   column1  column2
a        1        6
b        2        7
c        3        8
d        4        9
e        5       10
через двумерный массив NumPy
   column1  column2
a        1        6
b        2        7
c        3        8
d        4        9
e        5       10
структурированный массив NumPy
   column1  column2
0        1        6
1        2        7
2        3        8
3        4        9
4        5       10


### Index

Index - способ организации ссылки на данные объектов Series и DataFrame. 

Index - неизменяем, упорядочен, является мультимножеством(могут быть повторяющиеся значения)

In [26]:
ind = pd.Index([2, 3, 5, 7, 11])
print(ind)
print(ind[1])
print(ind[::2])

Index([2, 3, 5, 7, 11], dtype='int64')
3
Index([2, 5, 11], dtype='int64')


In [27]:
ind[1] = 5

TypeError: Index does not support mutable operations

Index - следует соглашениям объекта set (python)

In [30]:
indA = pd.Index([1, 2, 3, 4, 5])
indB = pd.Index([2, 3, 4, 5, 6])
print(indA.intersection(indB))

Index([2, 3, 4, 5], dtype='int64')


### Выборка данных из Series

Ведет себя как словарь

In [ ]:
data = pd.Series([0.25, 0.5, 0.75, 1], index=["a", "b", "c", "d"])
print("a" in data)
print("z" in data)
print(data.keys())
print(list(data.items()))
data["a"] = 100
data["z"] = 1000
print(data)

True
False
Index(['a', 'b', 'c', 'd'], dtype='object')
[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]
a     100.00
b       0.50
c       0.75
d       1.00
z    1000.00
dtype: float64


как одномерный массив

In [44]:
data = pd.Series([0.25, 0.5, 0.75, 1], index=["a", "b", "c", "d"])
print(data["a":"c"])
print(data[0:2])
print(data[data > 0.5])
print(data[(data > 0.5) & (data < 1)])
print(data[["a", "d"]])

a    0.25
b    0.50
c    0.75
dtype: float64
a    0.25
b    0.50
dtype: float64
c    0.75
d    1.00
dtype: float64
c    0.75
dtype: float64
a    0.25
d    1.00
dtype: float64


### Атрибуты-индексаторы

In [47]:
data = pd.Series([0.25, 0.5, 0.75, 1], index=[1, 3, 10, 15])
print(data[1])

0.25


In [48]:
print(data.loc[1])
print(data.iloc[1])

0.25
0.5


### Выборка данных из DataFrame

как словарь

In [53]:
popular_dict = {
    "city1": 1001,
    "city2": 1002,
    "city3": 1003,
    "city4": 1004,
    "city5": 1005,
}
area_dict = {
    "city1": 9991,
    "city2": 9992,
    "city3": 9993,
    "city4": 9994,
    "city5": 9995,
}
pop = pd.Series(popular_dict)
area = pd.Series(area_dict)
data = pd.DataFrame({"area": area, "pop": pop})
print(data)
print(data["area"])
print(data.area)

       area   pop
city1  9991  1001
city2  9992  1002
city3  9993  1003
city4  9994  1004
city5  9995  1005
city1    9991
city2    9992
city3    9993
city4    9994
city5    9995
Name: area, dtype: int64
city1    9991
city2    9992
city3    9993
city4    9994
city5    9995
Name: area, dtype: int64


In [54]:
print(data.pop is data["pop"])

False


In [56]:
data["new"] = data["area"]
print(data)

       area   pop   new
city1  9991  1001  9991
city2  9992  1002  9992
city3  9993  1003  9993
city4  9994  1004  9994
city5  9995  1005  9995


In [57]:
data["new1"] = data["area"] / data["pop"]
print(data)

       area   pop   new      new1
city1  9991  1001  9991  9.981019
city2  9992  1002  9992  9.972056
city3  9993  1003  9993  9.963111
city4  9994  1004  9994  9.954183
city5  9995  1005  9995  9.945274


как двумерный NumPy-массив

In [61]:
popular_dict = {
    "city1": 1001,
    "city2": 1002,
    "city3": 1003,
    "city4": 1004,
    "city5": 1005,
}
area_dict = {
    "city1": 9991,
    "city2": 9992,
    "city3": 9993,
    "city4": 9994,
    "city5": 9995,
}
pop = pd.Series(popular_dict)
area = pd.Series(area_dict)
data = pd.DataFrame({"area1": area, "pop1": pop})
print(data)
print(data.values)
print(data.T)

       area1  pop1
city1   9991  1001
city2   9992  1002
city3   9993  1003
city4   9994  1004
city5   9995  1005
[[9991 1001]
 [9992 1002]
 [9993 1003]
 [9994 1004]
 [9995 1005]]
       city1  city2  city3  city4  city5
area1   9991   9992   9993   9994   9995
pop1    1001   1002   1003   1004   1005


In [64]:
print(data["area1"])
print(data.values[0])
print(data.values[0:3])

city1    9991
city2    9992
city3    9993
city4    9994
city5    9995
Name: area1, dtype: int64
[9991 1001]
[[9991 1001]
 [9992 1002]
 [9993 1003]]


### Атрибуты-индексаторы

In [78]:
popular_dict = {
    "city1": 1001,
    "city2": 1002,
    "city3": 1003,
    "city4": 1004,
    "city5": 1005,
}
area_dict = {
    "city1": 9991,
    "city2": 9992,
    "city3": 9993,
    "city4": 9994,
    "city5": 9995,
}
pop = pd.Series(popular_dict)
area = pd.Series(area_dict)
data = pd.DataFrame({"area1": area, "pop1": pop, "pop": pop})
print(data)
print(data.iloc[:3, 1:2])
print(data.loc[:"city_4", "pop1":"pop"])
print(data.loc[data["pop"] > 1002, ["area1", "pop"]])
data.iloc[0, 2] = 9999
print(data)

       area1  pop1   pop
city1   9991  1001  1001
city2   9992  1002  1002
city3   9993  1003  1003
city4   9994  1004  1004
city5   9995  1005  1005
       pop1
city1  1001
city2  1002
city3  1003
       pop1   pop
city1  1001  1001
city2  1002  1002
city3  1003  1003
city4  1004  1004
city5  1005  1005
       area1   pop
city3   9993  1003
city4   9994  1004
city5   9995  1005
       area1  pop1   pop
city1   9991  1001  9999
city2   9992  1002  1002
city3   9993  1003  1003
city4   9994  1004  1004
city5   9995  1005  1005


In [95]:
rng = np.random.default_rng()
s = pd.Series(rng.integers(0, 10, 4))
print(s)

0    1
1    4
2    4
3    7
dtype: int64


In [96]:
print(np.exp(s))

0       2.718282
1      54.598150
2      54.598150
3    1096.633158
dtype: float64


In [98]:
popular_dict = {
    "city1": 1001,
    "city2": 1002,
    "city3": 1003,
    "city41": 1004,
    "city51": 1005,
}
area_dict = {
    "city1": 9991,
    "city2": 9992,
    "city3": 9993,
    "city42": 9994,
    "city52": 9995,
}
pop = pd.Series(popular_dict)
area = pd.Series(area_dict)
data = pd.DataFrame({"area1": area, "pop1": pop})
print(data)

         area1    pop1
city1   9991.0  1001.0
city2   9992.0  1002.0
city3   9993.0  1003.0
city41     NaN  1004.0
city42  9994.0     NaN
city51     NaN  1005.0
city52  9995.0     NaN


## 3. Объедините два объекта Series с неодинаковыми множествами ключей(индексов) так, чтобы вместе NaN было установлено значение 1

In [30]:
popular = pd.Series({
    "city1": 1001,
    "city2": 1002,
    "city3": 1003,
    "city41": 1004,
    "city51": 1005,
})
area = pd.Series({
    "city1": 9991,
    "city2": 9992,
    "city3": 9993,
    "city42": 9994,
    "city52": 9995,
})
data = pd.DataFrame({"area": area, "popular": popular}).fillna(1)
print(data)

          area  popular
city1   9991.0   1001.0
city2   9992.0   1002.0
city3   9993.0   1003.0
city41     1.0   1004.0
city42  9994.0      1.0
city51     1.0   1005.0
city52  9995.0      1.0


In [104]:
dfA = pd.DataFrame(rng.integers(0, 10, (2, 2)), columns=["a", "b"])
dfB = pd.DataFrame(rng.integers(0, 10, (3, 3)), columns=["a", "b", "c"])
print(dfA)
print(dfB)
print(dfA + dfB)

   a  b
0  7  4
1  7  6
   a  b  c
0  7  2  6
1  3  8  5
2  6  7  7
      a     b   c
0  14.0   6.0 NaN
1  10.0  14.0 NaN
2   NaN   NaN NaN


In [107]:
rng = np.random.default_rng(1)
A = rng.integers(0, 10, (3, 4))
print(A)
print(A[0])
print(A - A[0])

[[4 5 7 9]
 [0 1 8 9]
 [2 3 8 4]]
[4 5 7 9]
[[ 0  0  0  0]
 [-4 -4  1  0]
 [-2 -2  1 -5]]


In [113]:
df = pd.DataFrame(A, columns=["a", "b", "c", "d"])
print(df)
print(df.iloc[0])
print(df - df.iloc[0])
print(df.iloc[0, ::2])
print(df - df.iloc[0, ::2])

   a  b  c  d
0  4  5  7  9
1  0  1  8  9
2  2  3  8  4
a    4
b    5
c    7
d    9
Name: 0, dtype: int64
   a  b  c  d
0  0  0  0  0
1 -4 -4  1  0
2 -2 -2  1 -5
a    4
c    7
Name: 0, dtype: int64
     a   b    c   d
0  0.0 NaN  0.0 NaN
1 -4.0 NaN  1.0 NaN
2 -2.0 NaN  1.0 NaN


## 4. Переписать пример с транслированием для DataFrame так, чтобы вычитание происходило по столбцам

In [42]:
A = rng.integers(0, 10, (3, 4))
df = pd.DataFrame(A, columns=["a", "b", "c", "d"])

print("DataFrame:")
print(df)

print("Первый столбец:")
print(df.iloc[:, 0])

print("Вычитание по столбцам:")
print(df.sub(df.iloc[:, 0], axis=0))

DataFrame:
   a  b  c  d
0  2  8  2  4
1  6  5  0  0
2  8  7  8  5
Первый столбец:
0    2
1    6
2    8
Name: a, dtype: int64
Вычитание по столбцам:
   a  b  c  d
0  0  6  0  2
1  0 -1 -6 -6
2  0 -1  0 -3


### NA-значения: NaN, null, -99999

Pandas. Два способа хранения отсутсвующих значений

- индикаторы: NaN, None

- null

None - объект (накладные расходы). Не работает с sum, min

In [115]:
val1 = np.array([1, 2, 3])
print(val1.sum())

6


In [43]:
val1 = np.array([1, None, 2, 3])
print(val1.sum())

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [121]:
val1 = np.array([1, np.nan, 2, 3])
print(val1)
print(val1.sum())
print(np.sum(val1))
print(np.nansum(val1))

[ 1. nan  2.  3.]
nan
nan
6.0


In [124]:
x = pd.Series(range(10), dtype=int)
x[0] = None
x[1] = np.nan
print(x)

0    NaN
1    NaN
2    2.0
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64


In [134]:
x1 = pd.Series(["a", "b", "c"])
print(x1)
x1[0] = None
x1[1] = np.nan
print(x1)

0    a
1    b
2    c
dtype: object
0    None
1     NaN
2       c
dtype: object


In [135]:
x2 = pd.Series([1, 2, 3, np.nan, None, pd.NA])
print(x2)

0       1
1       2
2       3
3     NaN
4    None
5    <NA>
dtype: object


In [139]:
x3 = pd.Series([1, 2, 3, np.nan, None, pd.NA], dtype="Int32")
print(x3)

0       1
1       2
2       3
3    <NA>
4    <NA>
5    <NA>
dtype: Int32


In [143]:
print(x3.isnull())
print(x3[x3.isnull()])
print(x3[x3.notnull()])

0    False
1    False
2    False
3     True
4     True
5     True
dtype: bool
3    <NA>
4    <NA>
5    <NA>
dtype: Int32
0    1
1    2
2    3
dtype: Int32


In [144]:
print(x3.dropna())

0    1
1    2
2    3
dtype: Int32


In [148]:
df = pd.DataFrame(
    [[1, 2, 3, np.nan, None, pd.NA], 
     [1, 2, 3, 4, 5, 6], 
     [1,np.nan,3,4, np.nan, 6]]
)
print(df)
print(df.dropna())
print()
print(df.dropna(axis=0))
print(df.dropna(axis=1))

   0    1  2    3    4     5
0  1  2.0  3  NaN  NaN  <NA>
1  1  2.0  3  4.0  5.0     6
2  1  NaN  3  4.0  NaN     6
   0    1  2    3    4  5
1  1  2.0  3  4.0  5.0  6

   0    1  2    3    4  5
1  1  2.0  3  4.0  5.0  6
   0  2
0  1  3
1  1  3
2  1  3


how

- all - значения NA

- any - хотя бы одно значение 

- thresh - x, остается, если присутствует МИНИМУМ х непустых значений

In [149]:
print(df.dropna(axis=1,how='all'))

   0    1  2    3    4     5
0  1  2.0  3  NaN  NaN  <NA>
1  1  2.0  3  4.0  5.0     6
2  1  NaN  3  4.0  NaN     6


In [150]:
print(df.dropna(axis=1, how="any"))

   0  2
0  1  3
1  1  3
2  1  3


In [151]:
print(df.dropna(axis=1, thresh=2))

   0    1  2    3     5
0  1  2.0  3  NaN  <NA>
1  1  2.0  3  4.0     6
2  1  NaN  3  4.0     6


## 5. На примере объектов Series и DataFrame продемонстрируйте использование методов ffill() и bfill()

In [44]:
data = {
    "A": [1, np.nan, 3, np.nan, 5],
    "B": [np.nan, 7, np.nan, 9, np.nan],
    "C": [10, 20, np.nan, np.nan, 50],
}

df = pd.DataFrame(data)
print("Исходный DataFrame:")
print(df)

# ffill() заполняет пропуски ПОСЛЕДНИМ известным значением сверху вниз:
df1 = df.ffill()
print("После ffill():")
print(df1)

# bfill() заполняет пропуски СЛЕДУЮЩИМ известным значением снизу вверх:
df2 = df.bfill()
print("После bfill():")
print(df2)

Исходный DataFrame:
     A    B     C
0  1.0  NaN  10.0
1  NaN  7.0  20.0
2  3.0  NaN   NaN
3  NaN  9.0   NaN
4  5.0  NaN  50.0
После ffill():
     A    B     C
0  1.0  NaN  10.0
1  1.0  7.0  20.0
2  3.0  7.0  20.0
3  3.0  9.0  20.0
4  5.0  9.0  50.0
После bfill():
     A    B     C
0  1.0  7.0  10.0
1  3.0  7.0  20.0
2  3.0  9.0  50.0
3  5.0  9.0  50.0
4  5.0  NaN  50.0
